services:
  postgis:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: busdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d busdata"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgis
  
  etl:
    build:
      context: .
      dockerfile: etl/Dockerfile
    volumes:
      - ./etl:/app
      - ./dados:/app/dados
    depends_on:
      postgis:
        condition: service_healthy

networks:
  default:
    name: local-network
  
volumes:
  pgdata:
